import { and, desc, eq, inArray, sql } from "drizzle-orm";
import { ENV } from "./_core/env";
import { getDb } from "./db-connection";
export { getDb } from "./db-connection";
import { InsertUser, analyses, auditLogs, branches, commits, findingFeedback, findings, githubConnections, notifications, pullRequestRevisions, pullRequests, repositories, users, webhookDeliveries, workspaceMembers, workspaces } from "../drizzle/schema";
import type { AnalysisStatus, FindingFeedback, PrecheckResult } from "@shared/devflow-contracts";

export async function upsertUser(user: InsertUser): Promise<void> {
  if (!user.openId) throw new Error("User openId is required for upsert");
  const db = await getDb(); if (!db) return;
  const values: InsertUser = { openId: user.openId, name: user.name, email: user.email, loginMethod: user.loginMethod, lastSignedIn: user.lastSignedIn ?? new Date(), role: user.role ?? (user.openId === ENV.ownerOpenId ? "admin" : "user") };
  const updateSet: Record<string, unknown> = { lastSignedIn: values.lastSignedIn };
  if (user.name !== undefined) updateSet.name = user.name;
  if (user.email !== undefined) updateSet.email = user.email;
  if (user.loginMethod !== undefined) updateSet.loginMethod = user.loginMethod;
  await db.insert(users).values(values).onDuplicateKeyUpdate({ set: updateSet });
}
export async function getUserByOpenId(openId: string) { const db = await getDb(); if (!db) return undefined; const rows = await db.select().from(users).where(eq(users.openId, openId)).limit(1); return rows[0]; }

export async function ensureWorkspace(userId: number, name = "My Engineering Workspace") {
  const db = await getDb(); if (!db) return undefined;
  const existing = await db.select({ workspace: workspaces }).from(workspaces).innerJoin(workspaceMembers, eq(workspaceMembers.workspaceId, workspaces.id)).where(and(eq(workspaceMembers.userId, userId), eq(workspaceMembers.role, "OWNER"))).limit(1);
  if (existing[0]?.workspace) return existing[0].workspace;
  const inserted = await db.insert(workspaces).values({ name, createdById: userId });
  const id = Number(inserted[0].insertId);
  await db.insert(workspaceMembers).values({ workspaceId: id, userId, role: "OWNER" });
  const rows = await db.select().from(workspaces).where(eq(workspaces.id, id)).limit(1); return rows[0];
}
export async function listUserWorkspaces(userId: number) { const db = await getDb(); if (!db) return []; return db.select({ workspace: workspaces, membership: workspaceMembers }).from(workspaces).innerJoin(workspaceMembers, eq(workspaceMembers.workspaceId, workspaces.id)).where(eq(workspaceMembers.userId, userId)); }
export async function canAccessWorkspace(userId: number, workspaceId: number) { const db = await getDb(); if (!db) return false; const rows = await db.select().from(workspaceMembers).where(and(eq(workspaceMembers.userId, userId), eq(workspaceMembers.workspaceId, workspaceId))).limit(1); return !!rows[0]; }
export async function listWorkspaceMemberIds(workspaceId: number) { const db = await getDb(); if (!db) return []; const rows = await db.select({ userId: workspaceMembers.userId }).from(workspaceMembers).where(eq(workspaceMembers.workspaceId, workspaceId)); return rows.map(row => row.userId); }
export async function listWorkspaceMembers(workspaceId: number) { const db = await getDb(); if (!db) return []; return db.select({ userId: workspaceMembers.userId, name: users.name, email: users.email }).from(workspaceMembers).innerJoin(users, eq(users.id, workspaceMembers.userId)).where(eq(workspaceMembers.workspaceId, workspaceId)); }

export async function listRepositories(workspaceId: number) { const db = await getDb(); if (!db) return []; return db.select().from(repositories).where(eq(repositories.workspaceId, workspaceId)).orderBy(desc(repositories.updatedAt)); }
export async function getRepository(repositoryId: number) { const db = await getDb(); if (!db) return undefined; const rows = await db.select().from(repositories).where(eq(repositories.id, repositoryId)).limit(1); return rows[0]; }
export async function getRepositoryByGithubId(githubRepositoryId: number) { const db = await getDb(); if (!db) return undefined; const rows = await db.select().from(repositories).where(eq(repositories.githubRepositoryId, githubRepositoryId)).limit(1); return rows[0]; }
export async function connectRepository(input: typeof repositories.$inferInsert) { const db = await getDb(); if (!db) return undefined; const existing = await db.select().from(repositories).where(and(eq(repositories.workspaceId, input.workspaceId), eq(repositories.githubRepositoryId, input.githubRepositoryId))).limit(1); if (existing[0]) return existing[0]; const result = await db.insert(repositories).values(input); const rows = await db.select().from(repositories).where(eq(repositories.id, Number(result[0].insertId))).limit(1); return rows[0]; }
export async function upsertBranch(repositoryId: number, input: { githubBranchId: string; name: string; protected: boolean; latestSha?: string }) { const db = await getDb(); if (!db) return; const existing = await db.select().from(branches).where(and(eq(branches.repositoryId, repositoryId), eq(branches.githubBranchId, input.githubBranchId))).limit(1); if (existing[0]) { await db.update(branches).set({ ...input, protected: input.protected ? 1 : 0 }).where(eq(branches.id, existing[0].id)); return existing[0]; } const result = await db.insert(branches).values({ repositoryId, ...input, protected: input.protected ? 1 : 0 }); return (await db.select().from(branches).where(eq(branches.id, Number(result[0].insertId))).limit(1))[0]; }
export async function upsertCommit(repositoryId: number, input: { sha: string; message: string; author?: string | null; committedAt?: Date | null; htmlUrl?: string }) { const db = await getDb(); if (!db) return; const existing = await db.select().from(commits).where(and(eq(commits.repositoryId, repositoryId), eq(commits.sha, input.sha))).limit(1); if (existing[0]) return existing[0]; const result = await db.insert(commits).values({ repositoryId, ...input }); return (await db.select().from(commits).where(eq(commits.id, Number(result[0].insertId))).limit(1))[0]; }
export async function listBranches(repositoryId: number) { const db = await getDb(); if (!db) return []; return db.select().from(branches).where(eq(branches.repositoryId, repositoryId)).orderBy(desc(branches.updatedAt)); }
export async function listCommits(repositoryId: number) { const db = await getDb(); if (!db) return []; return db.select().from(commits).where(eq(commits.repositoryId, repositoryId)).orderBy(desc(commits.committedAt)).limit(100); }
export async function disconnectRepository(repositoryId: number) { const db = await getDb(); if (!db) return; await db.delete(repositories).where(eq(repositories.id, repositoryId)); }
export async function upsertGithubConnection(input: typeof githubConnections.$inferInsert) { const db = await getDb(); if (!db) return; const existing = await db.select().from(githubConnections).where(eq(githubConnections.userId, input.userId)).limit(1); if (existing[0]) { await db.update(githubConnections).set(input).where(eq(githubConnections.id, existing[0].id)); return; } await db.insert(githubConnections).values(input); }
export async function getGithubConnection(userId: number) { const db = await getDb(); if (!db) return undefined; const rows = await db.select().from(githubConnections).where(eq(githubConnections.userId, userId)).limit(1); return rows[0]; }

export async function upsertPullRequest(input: typeof pullRequests.$inferInsert) { const db = await getDb(); if (!db) return undefined; const existing = await db.select().from(pullRequests).where(and(eq(pullRequests.repositoryId, input.repositoryId), eq(pullRequests.githubPullRequestId, input.githubPullRequestId))).limit(1); if (existing[0]) { await db.update(pullRequests).set(input).where(eq(pullRequests.id, existing[0].id)); return { ...existing[0], ...input }; } const result = await db.insert(pullRequests).values(input); const rows = await db.select().from(pullRequests).where(eq(pullRequests.id, Number(result[0].insertId))).limit(1); return rows[0]; }
export async function listPullRequests(repositoryId: number) { const db = await getDb(); if (!db) return []; return db.select().from(pullRequests).where(eq(pullRequests.repositoryId, repositoryId)).orderBy(desc(pullRequests.updatedAt)); }
export async function getPullRequest(id: number) { const db = await getDb(); if (!db) return undefined; const rows = await db.select().from(pullRequests).where(eq(pullRequests.id, id)).limit(1); return rows[0]; }
export async function createRevision(input: typeof pullRequestRevisions.$inferInsert) { const db = await getDb(); if (!db) return undefined; const existing = await db.select().from(pullRequestRevisions).where(and(eq(pullRequestRevisions.pullRequestId, input.pullRequestId), eq(pullRequestRevisions.headSha, input.headSha))).limit(1); if (existing[0]) return existing[0]; const result = await db.insert(pullRequestRevisions).values(input); const rows = await db.select().from(pullRequestRevisions).where(eq(pullRequestRevisions.id, Number(result[0].insertId))).limit(1); return rows[0]; }

export async function findWebhookDelivery(deliveryId: string) { const db = await getDb(); if (!db) return undefined; const rows = await db.select().from(webhookDeliveries).where(eq(webhookDeliveries.githubDeliveryId, deliveryId)).limit(1); return rows[0]; }
export async function saveWebhookDelivery(input: typeof webhookDeliveries.$inferInsert) { const db = await getDb(); if (!db) return undefined; const result = await db.insert(webhookDeliveries).values(input); return Number(result[0].insertId); }
export async function markWebhookProcessed(id: number) { const db = await getDb(); if (db) await db.update(webhookDeliveries).set({ processedAt: new Date() }).where(eq(webhookDeliveries.id, id)); }

export async function createAnalysis(input: typeof analyses.$inferInsert) { const db = await getDb(); if (!db) return undefined; const existing = await db.select().from(analyses).where(eq(analyses.jobId, input.jobId)).limit(1); if (existing[0]) return existing[0]; const result = await db.insert(analyses).values(input); const rows = await db.select().from(analyses).where(eq(analyses.id, Number(result[0].insertId))).limit(1); return rows[0]; }
export async function updateAnalysis(id: number, values: Partial<typeof analyses.$inferInsert>) { const db = await getDb(); if (db) await db.update(analyses).set(values).where(eq(analyses.id, id)); }
export async function getAnalysis(id: number) { const db = await getDb(); if (!db) return undefined; const rows = await db.select().from(analyses).where(eq(analyses.id, id)).limit(1); return rows[0]; }
export async function listAnalysesForRepository(repositoryId: number) { const db = await getDb(); if (!db) return []; return db.select({ analysis: analyses, pullRequest: pullRequests }).from(analyses).innerJoin(pullRequestRevisions, eq(pullRequestRevisions.id, analyses.pullRequestRevisionId)).innerJoin(pullRequests, eq(pullRequests.id, pullRequestRevisions.pullRequestId)).where(eq(pullRequests.repositoryId, repositoryId)).orderBy(desc(analyses.createdAt)); }
export async function saveFindings(analysisId: number, items: Array<typeof findings.$inferInsert>) { const db = await getDb(); if (!db || items.length === 0) return []; await db.insert(findings).values(items.map(item => ({ ...item, analysisId }))); return listFindings(analysisId); }
export async function listFindings(analysisId: number) { const db = await getDb(); if (!db) return []; return db.select().from(findings).where(eq(findings.analysisId, analysisId)).orderBy(desc(findings.severity)); }
export async function setFindingFeedback(findingId: number, userId: number, feedback: FindingFeedback) { const db = await getDb(); if (!db) return; await db.update(findings).set({ status: feedback === "Accept" ? "ACCEPTED" : feedback === "Dismiss" ? "DISMISSED" : "INACCURATE" }).where(eq(findings.id, findingId)); await db.insert(findingFeedback).values({ findingId, userId, feedback }); }

export async function addNotification(input: typeof notifications.$inferInsert) { const db = await getDb(); if (!db) return; await db.insert(notifications).values(input); }
export async function listNotifications(userId: number) { const db = await getDb(); if (!db) return []; return db.select().from(notifications).where(eq(notifications.userId, userId)).orderBy(desc(notifications.createdAt)).limit(50); }
export async function markNotificationRead(id: number, userId: number) { const db = await getDb(); if (db) await db.update(notifications).set({ readAt: new Date() }).where(and(eq(notifications.id, id), eq(notifications.userId, userId))); }
export async function dashboardStats(repositoryId: number) { const db = await getDb(); if (!db) return { reviews: 0, completed: 0, findings: 0, accepted: 0, dismissed: 0, noTestUpdates: 0, medianLatencyMs: 0, byCategory: [], bySeverity: [] }; const reviewRows = await listAnalysesForRepository(repositoryId); const ids = reviewRows.map(row => row.analysis.id); const findingRows = ids.length ? await db.select().from(findings).where(inArray(findings.analysisId, ids)) : []; const completed = reviewRows.filter(row => row.analysis.status === "COMPLETED" || row.analysis.status === "PARTIAL").length; const latencies = reviewRows.map(row => row.analysis.latencyMs).filter((v): v is number => typeof v === "number").sort((a,b) => a-b); const medianLatencyMs = latencies.length ? latencies[Math.floor(latencies.length / 2)] : 0; const group = (key: "category" | "severity") => Object.entries(findingRows.reduce<Record<string, number>>((acc, item) => { const value = item[key]; acc[value] = (acc[value] ?? 0) + 1; return acc; }, {})).map(([label, count]) => ({ label, count })); const accepted = findingRows.filter(f => f.status === "ACCEPTED").length; const dismissed = findingRows.filter(f => f.status === "DISMISSED").length; const feedbackTotal = accepted + dismissed; const recurringRisks = Object.entries(findingRows.reduce<Record<string, { title: string; count: number; severity: string }>>((acc, item) => { const current = acc[item.fingerprint] ?? { title: item.title, count: 0, severity: item.severity }; current.count += 1; acc[item.fingerprint] = current; return acc; }, {})).filter(([, value]) => value.count > 1).map(([fingerprint, value]) => ({ fingerprint, ...value })).sort((a, b) => b.count - a.count).slice(0, 6); return { reviews: reviewRows.length, completed, findings: findingRows.length, accepted, dismissed, acceptedRate: feedbackTotal ? Math.round((accepted / feedbackTotal) * 100) : 0, dismissedRate: feedbackTotal ? Math.round((dismissed / feedbackTotal) * 100) : 0, noTestUpdates: reviewRows.filter(row => Array.isArray(row.analysis.precheckResults) && (row.analysis.precheckResults as PrecheckResult[]).some(x => x.key === "missing_tests" && !x.passed)).length, medianLatencyMs, byCategory: group("category"), bySeverity: group("severity"), recentReviews: reviewRows.slice(0, 6).map(row => ({ id: row.analysis.id, status: row.analysis.status, summary: row.analysis.summary, createdAt: row.analysis.createdAt, prNumber: row.pullRequest.number, title: row.pullRequest.title })), recurringRisks }; }
