import crypto from "node:crypto";
import { z } from "zod";
import { ENV } from "./_core/env";
import { consumeSharedWorkspaceBudget } from "./budget";

export const CONTEXT_POLICY = { maxDiffChars: 60_000, maxChangedFiles: 30, maxPatchCharsPerFile: 8_000, maxNearbyTests: 8, maxTestChars: 5_000, maxManifests: 8, maxManifestChars: 4_000 } as const;
export const reviewPartition = { deterministic: ["test_coverage", "large_change", "secret_pattern", "migration_schema", "authorization_sensitive", "console_log", "unused_import"], reasoning: ["logic_bug", "security_edge_case", "missing_edge_case", "api_contract", "performance_tradeoff"] } as const;
export const benchmarkCaseSchema = z.object({ id: z.string(), description: z.string(), clean: z.boolean(), expectedFindingCategories: z.array(z.string()), expectedFingerprints: z.array(z.string()).default([]) });
export type BenchmarkCase = z.infer<typeof benchmarkCaseSchema>;
export const benchmarkResultSchema = z.object({ cases: z.number().int().nonnegative(), predictedFindings: z.number().int().nonnegative(), truePositives: z.number().int().nonnegative(), falsePositives: z.number().int().nonnegative(), falseNegatives: z.number().int().nonnegative(), precision: z.number().min(0).max(1), recall: z.number().min(0).max(1), falsePositiveRate: z.number().min(0).max(1) });
export type BenchmarkResult = z.infer<typeof benchmarkResultSchema>;

export function normalizeCodeSnippet(value: string) { return value.replace(/\r\n/g, "\n").replace(/\s+/g, " ").replace(/\/\/.*$/gm, "").trim().toLowerCase(); }
export function stableFindingFingerprint(input: { category: string; filePath?: string | null; title: string; evidence: string; codeSnippet?: string | null }) { return crypto.createHash("sha256").update([input.category, (input.filePath || "").replace(/\\/g, "/").toLowerCase(), input.title.trim().toLowerCase(), normalizeCodeSnippet(input.codeSnippet || input.evidence)].join("\n")).digest("hex"); }
export function evaluateBenchmark(cases: BenchmarkCase[], predicted: Array<{ caseId: string; category: string; fingerprint?: string }>): BenchmarkResult { let tp = 0; let fp = 0; let fn = 0; for (const item of cases) { const rows = predicted.filter(prediction => prediction.caseId === item.id); const expected = new Set(item.expectedFindingCategories); const actual = new Set(rows.map(row => row.category)); Array.from(actual).forEach(category => { if (category && expected.has(category)) tp++; else fp++; }); Array.from(expected).forEach(category => { if (!actual.has(category)) fn++; }); if (item.clean && rows.length) fp += rows.length; } const predictedFindings = predicted.length; const precision = tp + fp ? tp / (tp + fp) : 1; const recall = tp + fn ? tp / (tp + fn) : 1; const cleanCases = cases.filter(item => item.clean).length; const falsePositiveRate = cleanCases ? predicted.filter(row => cases.find(item => item.id === row.caseId)?.clean).length / cleanCases : 0; return benchmarkResultSchema.parse({ cases: cases.length, predictedFindings, truePositives: tp, falsePositives: fp, falseNegatives: fn, precision, recall, falsePositiveRate }); }

export async function consumeWorkspaceBudget(workspaceId: number, estimatedTokens: number, dailyCap = ENV.aiDailyTokenCap) { return consumeSharedWorkspaceBudget(workspaceId, estimatedTokens, dailyCap); }

export type DeterministicPlugin = { language: string; run: (files: Array<{ filename: string; patch?: string | null }>) => Array<{ key: string; passed: boolean; severity: "info" | "low" | "medium" | "high" | "critical"; message: string; files: string[] }> };
export const typescriptDeterministicPlugin: DeterministicPlugin = { language: "typescript", run(files) { const findings: Array<{ key: string; passed: boolean; severity: "info" | "low" | "medium" | "high" | "critical"; message: string; files: string[] }> = []; const consoleFiles = files.filter(file => /\bconsole\.log\s*\(/.test(file.patch || "")).map(file => file.filename); findings.push({ key: "console_log", passed: consoleFiles.length === 0, severity: "low", message: consoleFiles.length ? "console.log usage was detected in the changed patch." : "No console.log usage detected.", files: consoleFiles }); return findings; } };
export function deterministicPluginForFiles(files: Array<{ filename: string }>) { return files.some(file => /\.(ts|tsx|js|jsx)$/.test(file.filename)) ? typescriptDeterministicPlugin : undefined; }
