import { z } from "zod";
import { parse as parseCookie } from "cookie";
import { COOKIE_NAME } from "@shared/const";
import { getSessionCookieOptions } from "./_core/cookies";
import { systemRouter } from "./_core/systemRouter";
import { protectedProcedure, publicProcedure, router } from "./_core/trpc";
import { ENV } from "./_core/env";
import { createGithubCheckRun, createPullRequestReviewComment, listAccessibleRepositories, getRepositoryBranches, getRepositoryCommits, getRepositoryPullRequests } from "./github";
import { addNotification, canAccessWorkspace, dashboardStats, disconnectRepository, ensureWorkspace, getAnalysis, getGithubConnection, getPullRequest, getRepository, listAnalysesForRepository, listFindings, listNotifications, listPullRequests, listRepositories, listUserWorkspaces, markNotificationRead, setFindingFeedback, upsertGithubConnection, connectRepository, upsertBranch, upsertCommit, listBranches, listCommits } from "./db";
import { enqueueAnalysis } from "./queue";
import { feedbackSchema } from "@shared/devflow-contracts";
import { architectureModules, deriveFindingLifecycle, findingFingerprint, impactedTests, normalizePolicy, ownerMatches, parseCodeowners, policyBlocksFindings, safeExternalAdapter } from "./second-release";
import { addSecondReleaseAuditLog, createEngineeringReport, createEvaluationDataset, createOnboardingScan, evaluationSummary, findPublishedComment, getReviewComment, latestLifecycleForFingerprint, latestReviewPolicy, listArchitectureModules, listCiChecks, listCodeOwners, listDependencyRisks, listEngineeringReports, listEvaluationDatasets, listEvaluationSamples, getEvaluationDataset, listFindingLifecycle, listIntegrationConfigs, listOnboardingScans, getReviewerAssignment, listReviewerAssignments, listReviewerAssignmentsForRepository, listReviewComments, listTestImpacts, saveAnalysisEvaluation, saveArchitectureModules, saveCiCheck, saveCodeOwners, saveDependencyRisk, saveEvaluationSample, saveFindingLifecycle, saveIntegrationConfig, saveReviewComment, saveReviewPolicy, saveReviewerAssignment, updateFindingLifecycleStatus, updateReviewerAssignment, updateReviewComment } from "./second-release-db";
import { runOnboardingScan } from "./onboarding";
import { storagePut } from "./storage";
import { deliverNotification, parseSecurityToolOutput, securityToolProvider } from "./security-and-notifications";

const workspaceInput = z.object({ workspaceId: z.number().int().positive() });
export function defaultWorkspaceName(name?: string | null) { return `${name || "My"} Engineering Workspace`; }
async function assertWorkspace(userId: number, workspaceId: number) { if (!(await canAccessWorkspace(userId, workspaceId))) throw new Error("Workspace access denied"); }

export const appRouter = router({
  system: systemRouter,
  auth: router({
    me: publicProcedure.query(async opts => { if (opts.ctx.user) await ensureWorkspace(opts.ctx.user.id, defaultWorkspaceName(opts.ctx.user.name)); return opts.ctx.user; }),
    logout: publicProcedure.mutation(({ ctx }) => { const cookieOptions = getSessionCookieOptions(ctx.req); ctx.res.clearCookie(COOKIE_NAME, { ...cookieOptions, maxAge: -1 }); return { success: true } as const; }),
  }),
  workspace: router({
    list: protectedProcedure.query(({ ctx }) => listUserWorkspaces(ctx.user.id)),
    bootstrap: protectedProcedure.mutation(({ ctx }) => ensureWorkspace(ctx.user.id, defaultWorkspaceName(ctx.user.name))),
  }),
  github: router({
    status: protectedProcedure.query(async ({ ctx }) => ({ configured: Boolean(ENV.githubClientId), connected: Boolean(await getGithubConnection(ctx.user.id)) })),
    connectToken: protectedProcedure.input(z.object({ accessToken: z.string().min(1).optional(), githubLogin: z.string().optional() })).mutation(async ({ ctx, input }) => { const cookies = parseCookie(ctx.req.headers.cookie || ""); const accessToken = input.accessToken || cookies.devflow_github_token; if (!accessToken) throw new Error("GitHub OAuth is not configured or no access token is available"); await upsertGithubConnection({ userId: ctx.user.id, accessToken, githubLogin: input.githubLogin, scopes: "repo,read:user" }); return { success: true }; }),
    accessibleRepositories: protectedProcedure.query(async ({ ctx }) => { const connection = await getGithubConnection(ctx.user.id); if (!connection?.accessToken) return []; return listAccessibleRepositories(connection.accessToken); }),
  }),
  repository: router({
    list: protectedProcedure.input(workspaceInput).query(async ({ ctx, input }) => { await assertWorkspace(ctx.user.id, input.workspaceId); return listRepositories(input.workspaceId); }),
    connect: protectedProcedure.input(z.object({ workspaceId: z.number().int().positive(), githubRepositoryId: z.number().int(), owner: z.string(), name: z.string(), fullName: z.string(), defaultBranch: z.string(), isPrivate: z.boolean().default(false) })).mutation(async ({ ctx, input }) => { await assertWorkspace(ctx.user.id, input.workspaceId); return connectRepository({ ...input, isPrivate: input.isPrivate ? 1 : 0, syncStatus: "IDLE" }); }),
    disconnect: protectedProcedure.input(z.object({ repositoryId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const repository = await getRepository(input.repositoryId); if (!repository) throw new Error("Repository not found"); await assertWorkspace(ctx.user.id, repository.workspaceId); await disconnectRepository(input.repositoryId); return { success: true }; }),
    sync: protectedProcedure.input(z.object({ repositoryId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const repository = await getRepository(input.repositoryId); if (!repository) throw new Error("Repository not found"); await assertWorkspace(ctx.user.id, repository.workspaceId); const connection = await getGithubConnection(ctx.user.id); if (!connection?.accessToken) throw new Error("Connect GitHub before synchronizing"); const [prs, branches, commits] = await Promise.all([getRepositoryPullRequests(connection.accessToken, repository.owner, repository.name), getRepositoryBranches(connection.accessToken, repository.owner, repository.name), getRepositoryCommits(connection.accessToken, repository.owner, repository.name)]); for (const pr of prs) await (await import("./db")).upsertPullRequest({ repositoryId: repository.id, ...pr }); for (const branch of branches) await upsertBranch(repository.id, branch); for (const commit of commits) await upsertCommit(repository.id, commit); return { syncedPullRequests: prs.length, syncedBranches: branches.length, syncedCommits: commits.length }; }),
    branches: protectedProcedure.input(z.object({ repositoryId: z.number().int().positive() })).query(async ({ ctx, input }) => { const repository = await getRepository(input.repositoryId); if (!repository) throw new Error("Repository not found"); await assertWorkspace(ctx.user.id, repository.workspaceId); return listBranches(input.repositoryId); }),
    commits: protectedProcedure.input(z.object({ repositoryId: z.number().int().positive() })).query(async ({ ctx, input }) => { const repository = await getRepository(input.repositoryId); if (!repository) throw new Error("Repository not found"); await assertWorkspace(ctx.user.id, repository.workspaceId); return listCommits(input.repositoryId); }),
    pullRequests: protectedProcedure.input(z.object({ repositoryId: z.number().int().positive() })).query(async ({ ctx, input }) => { const repository = await getRepository(input.repositoryId); if (!repository) throw new Error("Repository not found"); await assertWorkspace(ctx.user.id, repository.workspaceId); return listPullRequests(input.repositoryId); }),
    health: protectedProcedure.input(z.object({ repositoryId: z.number().int().positive() })).query(async ({ ctx, input }) => { const repository = await getRepository(input.repositoryId); if (!repository) throw new Error("Repository not found"); await assertWorkspace(ctx.user.id, repository.workspaceId); return dashboardStats(input.repositoryId); }),
    reviews: protectedProcedure.input(z.object({ repositoryId: z.number().int().positive() })).query(async ({ ctx, input }) => { const repository = await getRepository(input.repositoryId); if (!repository) throw new Error("Repository not found"); await assertWorkspace(ctx.user.id, repository.workspaceId); return listAnalysesForRepository(input.repositoryId); }),
  }),
  pullRequest: router({
    detail: protectedProcedure.input(z.object({ pullRequestId: z.number().int().positive() })).query(async ({ ctx, input }) => { const pr = await getPullRequest(input.pullRequestId); if (!pr) throw new Error("Pull request not found"); const repo = await getRepository(pr.repositoryId); if (!repo) throw new Error("Repository not found"); await assertWorkspace(ctx.user.id, repo.workspaceId); const connection = await getGithubConnection(ctx.user.id); let files: Array<{ filename: string; status?: string; additions?: number; deletions?: number; patch?: string | null }> = []; let diff = ""; if (connection?.accessToken) { files = await (await import("./github")).getPullRequestFiles(connection.accessToken, repo.owner, repo.name, pr.number); diff = await (await import("./github")).getPullRequestDiff(connection.accessToken, repo.owner, repo.name, pr.number); } return { ...pr, repository: repo, files, diff }; }),
    analyze: protectedProcedure.input(z.object({ pullRequestId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const pr = await getPullRequest(input.pullRequestId); if (!pr) throw new Error("Pull request not found"); const repo = await getRepository(pr.repositoryId); if (!repo) throw new Error("Repository not found"); await assertWorkspace(ctx.user.id, repo.workspaceId); return enqueueAnalysis({ repositoryId: repo.id, pullRequestId: pr.id, pullRequestNumber: pr.number, headSha: pr.headSha, baseSha: pr.baseSha, changedFilesCount: pr.changedFiles, additions: pr.additions, deletions: pr.deletions }); }),
  }),
  analysis: router({
    detail: protectedProcedure.input(z.object({ analysisId: z.number().int().positive() })).query(async ({ ctx, input }) => { const analysis = await getAnalysis(input.analysisId); if (!analysis) throw new Error("Analysis not found"); const findings = await listFindings(input.analysisId); return { analysis, findings }; }),
  }),
  finding: router({
    feedback: protectedProcedure.input(z.object({ findingId: z.number().int().positive(), feedback: feedbackSchema })).mutation(async ({ ctx, input }) => { await setFindingFeedback(input.findingId, ctx.user.id, input.feedback); await updateFindingLifecycleStatus(input.findingId, input.feedback === "Accept" ? "ACCEPTED" : input.feedback === "Dismiss" ? "DISMISSED" : "INACCURATE"); return { success: true, feedback: input.feedback }; }),
  }),
  notification: router({
    list: protectedProcedure.query(({ ctx }) => listNotifications(ctx.user.id)),
    read: protectedProcedure.input(z.object({ notificationId: z.number().int().positive() })).mutation(({ ctx, input }) => markNotificationRead(input.notificationId, ctx.user.id).then(() => ({ success: true }))),
  }),
  policy: router({
    get: protectedProcedure.input(z.object({ repositoryId: z.number().int().positive() })).query(async ({ ctx, input }) => { const repository = await getRepository(input.repositoryId); if (!repository) throw new Error("Repository not found"); await assertWorkspace(ctx.user.id, repository.workspaceId); return latestReviewPolicy(input.repositoryId); }),
    save: protectedProcedure.input(z.object({ repositoryId: z.number().int().positive(), policy: z.object({ minimumBlockingSeverity: z.enum(["critical", "high", "medium", "low", "info"]), requireTestsFor: z.array(z.string()), ignoredPaths: z.array(z.string()), enabledPrechecks: z.array(z.string()), maximumPrSize: z.number().int().positive(), blockOnSecrets: z.boolean(), postInlineComments: z.boolean() }) })).mutation(async ({ ctx, input }) => { const repository = await getRepository(input.repositoryId); if (!repository) throw new Error("Repository not found"); await assertWorkspace(ctx.user.id, repository.workspaceId); const previous = await latestReviewPolicy(input.repositoryId); const policy = normalizePolicy(input.policy); return saveReviewPolicy({ repositoryId: input.repositoryId, version: (previous?.version || 0) + 1, minimumBlockingSeverity: policy.minimumBlockingSeverity, requireTestsFor: policy.requireTestsFor, ignoredPaths: policy.ignoredPaths, enabledPrechecks: policy.enabledPrechecks, maximumPrSize: policy.maximumPrSize, blockOnSecrets: policy.blockOnSecrets ? 1 : 0, postInlineComments: policy.postInlineComments ? 1 : 0, createdById: ctx.user.id }); }),
  }),
  lifecycle: router({
    list: protectedProcedure.input(z.object({ repositoryId: z.number().int().positive() })).query(async ({ ctx, input }) => { const repository = await getRepository(input.repositoryId); if (!repository) throw new Error("Repository not found"); await assertWorkspace(ctx.user.id, repository.workspaceId); return listFindingLifecycle(input.repositoryId); }),
    fingerprint: protectedProcedure.input(z.object({ repositoryId: z.number().int().positive(), findingId: z.number().int().positive(), category: z.string(), filePath: z.string().nullable().optional(), title: z.string(), evidence: z.string(), previous: z.object({ fingerprint: z.string(), status: z.string().optional() }).optional() })).mutation(async ({ ctx, input }) => { const repository = await getRepository(input.repositoryId); if (!repository) throw new Error("Repository not found"); await assertWorkspace(ctx.user.id, repository.workspaceId); const fingerprint = findingFingerprint(input); const lifecycle = deriveFindingLifecycle(input.previous, fingerprint); await saveFindingLifecycle({ findingId: input.findingId, repositoryId: input.repositoryId, fingerprint, lifecycle, previousFindingId: undefined }); return { fingerprint, lifecycle }; }),
  }),
  comment: router({
    list: protectedProcedure.input(z.object({ repositoryId: z.number().int().positive() })).query(async ({ ctx, input }) => { const repository = await getRepository(input.repositoryId); if (!repository) throw new Error("Repository not found"); await assertWorkspace(ctx.user.id, repository.workspaceId); return listReviewComments(input.repositoryId); }),
    draft: protectedProcedure.input(z.object({ findingId: z.number().int().positive(), repositoryId: z.number().int().positive(), filePath: z.string(), line: z.number().int().positive().nullable().optional(), body: z.string().min(1) })).mutation(async ({ ctx, input }) => { const repository = await getRepository(input.repositoryId); if (!repository) throw new Error("Repository not found"); await assertWorkspace(ctx.user.id, repository.workspaceId); return saveReviewComment({ ...input, status: "DRAFT", createdById: ctx.user.id }); }),
    publish: protectedProcedure.input(z.object({ commentId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const comment = await getReviewComment(input.commentId); if (!comment) throw new Error("Comment not found"); const duplicate = await findPublishedComment(comment.findingId); if (duplicate) return { status: "ALREADY_PUBLISHED", githubCommentId: duplicate.githubCommentId }; const repository = await getRepository(comment.repositoryId); if (!repository) throw new Error("Repository not found"); await assertWorkspace(ctx.user.id, repository.workspaceId); const connection = await getGithubConnection(ctx.user.id); const pullRequests = await listPullRequests(repository.id); const pullRequest = pullRequests.find(item => item.headSha === (comment.githubCommentId || "")) || pullRequests[0]; if (!connection?.accessToken) return updateReviewComment(comment.id, { status: "SKIPPED" }).then(() => ({ status: "NOT_CONFIGURED", message: "Add GitHub credentials to publish approved comments." })); if (!pullRequest) throw new Error("No pull request available for comment"); const published = await createPullRequestReviewComment(connection.accessToken, repository.owner, repository.name, pullRequest.number, comment.body, pullRequest.headSha, comment.filePath, comment.line || undefined); await updateReviewComment(comment.id, { status: "PUBLISHED", githubCommentId: published.id, publishedAt: new Date() }); await addSecondReleaseAuditLog({ workspaceId: repository.workspaceId, userId: ctx.user.id, action: "github.comment.published", entityType: "githubReviewComment", entityId: comment.id, metadata: { githubCommentId: published.id, filePath: comment.filePath } }); return { status: "PUBLISHED", ...published }; }),
  }),
  ownership: router({
    parse: protectedProcedure.input(z.object({ repositoryId: z.number().int().positive(), content: z.string() })).mutation(async ({ ctx, input }) => { const repository = await getRepository(input.repositoryId); if (!repository) throw new Error("Repository not found"); await assertWorkspace(ctx.user.id, repository.workspaceId); const owners = parseCodeowners(input.content); await saveCodeOwners(input.repositoryId, owners); return owners; }),
    list: protectedProcedure.input(z.object({ repositoryId: z.number().int().positive() })).query(async ({ ctx, input }) => { const repository = await getRepository(input.repositoryId); if (!repository) throw new Error("Repository not found"); await assertWorkspace(ctx.user.id, repository.workspaceId); return listCodeOwners(input.repositoryId); }),
    match: protectedProcedure.input(z.object({ repositoryId: z.number().int().positive(), filePath: z.string() })).query(async ({ ctx, input }) => { const repository = await getRepository(input.repositoryId); if (!repository) throw new Error("Repository not found"); await assertWorkspace(ctx.user.id, repository.workspaceId); return (await listCodeOwners(input.repositoryId)).filter(owner => ownerMatches(owner.pattern, input.filePath)); }),
  }),
  insights: router({
    architecture: protectedProcedure.input(z.object({ repositoryId: z.number().int().positive(), files: z.array(z.string()).default([]) })).mutation(async ({ ctx, input }) => { const repository = await getRepository(input.repositoryId); if (!repository) throw new Error("Repository not found"); await assertWorkspace(ctx.user.id, repository.workspaceId); const modules = architectureModules(input.files); await saveArchitectureModules(input.repositoryId, modules); return modules; }),
    architectureList: protectedProcedure.input(z.object({ repositoryId: z.number().int().positive() })).query(async ({ ctx, input }) => { const repository = await getRepository(input.repositoryId); if (!repository) throw new Error("Repository not found"); await assertWorkspace(ctx.user.id, repository.workspaceId); return listArchitectureModules(input.repositoryId); }),
    dependencies: protectedProcedure.input(z.object({ repositoryId: z.number().int().positive(), packageName: z.string(), currentVersion: z.string().optional(), severity: z.string(), source: z.string(), details: z.string().optional() })).mutation(async ({ ctx, input }) => { const repository = await getRepository(input.repositoryId); if (!repository) throw new Error("Repository not found"); await assertWorkspace(ctx.user.id, repository.workspaceId); return saveDependencyRisk({ ...input, status: "OPEN" }); }),
    dependencyList: protectedProcedure.input(z.object({ repositoryId: z.number().int().positive() })).query(async ({ ctx, input }) => { const repository = await getRepository(input.repositoryId); if (!repository) throw new Error("Repository not found"); await assertWorkspace(ctx.user.id, repository.workspaceId); return listDependencyRisks(input.repositoryId); }),
    testImpact: protectedProcedure.input(z.object({ files: z.array(z.string()), availableTests: z.array(z.string()) })).query(({ input }) => impactedTests(input.files, input.availableTests)),
  }),
  security: router({
    parse: protectedProcedure.input(z.object({ provider: securityToolProvider, payload: z.unknown() })).query(({ input }) => parseSecurityToolOutput(input.provider, input.payload)),
  }),
  evaluation: router({
    datasets: protectedProcedure.input(z.object({ workspaceId: z.number().int().positive() })).query(async ({ ctx, input }) => { await assertWorkspace(ctx.user.id, input.workspaceId); return listEvaluationDatasets(input.workspaceId); }),
    createDataset: protectedProcedure.input(z.object({ workspaceId: z.number().int().positive(), name: z.string().trim().min(1).max(120), description: z.string().trim().max(1000).optional() })).mutation(async ({ ctx, input }) => { await assertWorkspace(ctx.user.id, input.workspaceId); return createEvaluationDataset(input); }),
    samples: protectedProcedure.input(z.object({ datasetId: z.number().int().positive(), workspaceId: z.number().int().positive() })).query(async ({ ctx, input }) => { await assertWorkspace(ctx.user.id, input.workspaceId); const dataset = await getEvaluationDataset(input.datasetId); if (!dataset || dataset.workspaceId !== input.workspaceId) throw new Error("Evaluation dataset not found"); return listEvaluationSamples(input.datasetId); }),
    addSample: protectedProcedure.input(z.object({ workspaceId: z.number().int().positive(), datasetId: z.number().int().positive(), analysisId: z.number().int().positive(), findingId: z.number().int().positive().optional(), reviewerLabel: z.string().trim().min(1).max(80), modelLabel: z.string().trim().max(80).optional(), falsePositive: z.boolean().optional() })).mutation(async ({ ctx, input }) => { await assertWorkspace(ctx.user.id, input.workspaceId); const dataset = await getEvaluationDataset(input.datasetId); if (!dataset || dataset.workspaceId !== input.workspaceId) throw new Error("Evaluation dataset not found"); const analysis = await getAnalysis(input.analysisId); if (!analysis) throw new Error("Analysis not found"); return saveEvaluationSample({ ...input, falsePositive: input.falsePositive === undefined ? null : input.falsePositive ? 1 : 0 }); }),
    record: protectedProcedure.input(z.object({ analysisId: z.number().int().positive(), findingId: z.number().int().positive().optional(), reviewerLabel: z.string().optional(), modelLabel: z.string().optional(), datasetName: z.string().default("production"), agreement: z.boolean().optional(), falsePositive: z.boolean().optional(), latencyMs: z.number().int().nonnegative().optional(), estimatedCost: z.string().optional() })).mutation(async ({ ctx, input }) => { const analysis = await getAnalysis(input.analysisId); if (!analysis) throw new Error("Analysis not found"); return saveAnalysisEvaluation({ ...input, agreement: input.agreement === undefined ? null : input.agreement ? 1 : 0, falsePositive: input.falsePositive === undefined ? null : input.falsePositive ? 1 : 0 }); }),
    summary: protectedProcedure.input(z.object({ analysisId: z.number().int().positive() })).query(({ input }) => evaluationSummary(input.analysisId)),
    testImpacts: protectedProcedure.input(z.object({ analysisId: z.number().int().positive() })).query(({ input }) => listTestImpacts(input.analysisId)),
  }),
  reviewer: router({
    list: protectedProcedure.input(z.object({ pullRequestId: z.number().int().positive() })).query(async ({ ctx, input }) => { const pr = await getPullRequest(input.pullRequestId); if (!pr) throw new Error("Pull request not found"); const repository = await getRepository(pr.repositoryId); if (!repository) throw new Error("Repository not found"); await assertWorkspace(ctx.user.id, repository.workspaceId); return listReviewerAssignments(input.pullRequestId); }),
    repositoryList: protectedProcedure.input(z.object({ repositoryId: z.number().int().positive() })).query(async ({ ctx, input }) => { const repository = await getRepository(input.repositoryId); if (!repository) throw new Error("Repository not found"); await assertWorkspace(ctx.user.id, repository.workspaceId); return listReviewerAssignmentsForRepository(input.repositoryId); }),
    create: protectedProcedure.input(z.object({ pullRequestId: z.number().int().positive(), repositoryId: z.number().int().positive(), owner: z.string().trim().min(1).max(160), userId: z.number().int().positive().optional(), source: z.string().default("MANUAL") })).mutation(async ({ ctx, input }) => { const repository = await getRepository(input.repositoryId); if (!repository) throw new Error("Repository not found"); await assertWorkspace(ctx.user.id, repository.workspaceId); return saveReviewerAssignment({ ...input, status: input.userId ? "ASSIGNED" : "RECOMMENDED" }); }),
    update: protectedProcedure.input(z.object({ assignmentId: z.number().int().positive(), status: z.enum(["ASSIGNED", "DISMISSED"]) })).mutation(async ({ ctx, input }) => { const assignment = await getReviewerAssignment(input.assignmentId); if (!assignment) throw new Error("Reviewer assignment not found"); const repository = await getRepository(assignment.repositoryId); if (!repository) throw new Error("Repository not found"); await assertWorkspace(ctx.user.id, repository.workspaceId); return updateReviewerAssignment(input.assignmentId, input.status); }),
  }),
  ci: router({
    list: protectedProcedure.input(z.object({ repositoryId: z.number().int().positive() })).query(async ({ ctx, input }) => { const repository = await getRepository(input.repositoryId); if (!repository) throw new Error("Repository not found"); await assertWorkspace(ctx.user.id, repository.workspaceId); return listCiChecks(input.repositoryId); }),
    evaluate: protectedProcedure.input(z.object({ repositoryId: z.number().int().positive(), analysisId: z.number().int().positive(), findings: z.array(z.object({ severity: z.string(), category: z.string() })), headSha: z.string().optional() })).mutation(async ({ ctx, input }) => { const repository = await getRepository(input.repositoryId); if (!repository) throw new Error("Repository not found"); await assertWorkspace(ctx.user.id, repository.workspaceId); const policy = await latestReviewPolicy(input.repositoryId); const normalized = normalizePolicy(policy ? { minimumBlockingSeverity: policy.minimumBlockingSeverity as "critical" | "high" | "medium" | "low" | "info", requireTestsFor: (policy.requireTestsFor as string[]) || undefined, ignoredPaths: (policy.ignoredPaths as string[]) || undefined, enabledPrechecks: (policy.enabledPrechecks as string[]) || undefined, maximumPrSize: policy.maximumPrSize, blockOnSecrets: Boolean(policy.blockOnSecrets), postInlineComments: Boolean(policy.postInlineComments) } : {}); const blocking = policyBlocksFindings(normalized, input.findings); const connection = await getGithubConnection(ctx.user.id); const pullRequest = (await listPullRequests(repository.id))[0]; let githubCheckRunId: string | undefined; let detailsUrl: string | null = `/pull-requests/${input.analysisId}`; if (connection?.accessToken && pullRequest && input.headSha) { const remote = await createGithubCheckRun(connection.accessToken, repository.owner, repository.name, "DevFlow AI", input.headSha, blocking.length ? "failure" : "success", `${blocking.length} policy-blocking findings`); githubCheckRunId = remote.id; detailsUrl = remote.url; } const check = await saveCiCheck({ analysisId: input.analysisId, repositoryId: input.repositoryId, githubCheckRunId, conclusion: blocking.length ? "failure" : "success", blockingFindings: blocking.length, detailsUrl }); return { ...check, blockingFindings: blocking, githubStatus: githubCheckRunId ? "PUBLISHED" : "NOT_CONFIGURED" }; }),
  }),
  onboarding: router({
    list: protectedProcedure.input(z.object({ repositoryId: z.number().int().positive() })).query(async ({ ctx, input }) => { const repository = await getRepository(input.repositoryId); if (!repository) throw new Error("Repository not found"); await assertWorkspace(ctx.user.id, repository.workspaceId); return listOnboardingScans(input.repositoryId); }),
    start: protectedProcedure.input(z.object({ repositoryId: z.number().int().positive(), summary: z.string().optional() })).mutation(async ({ ctx, input }) => { const repository = await getRepository(input.repositoryId); if (!repository) throw new Error("Repository not found"); await assertWorkspace(ctx.user.id, repository.workspaceId); const scan = await createOnboardingScan({ repositoryId: input.repositoryId, status: "QUEUED", summary: input.summary || "Baseline scan queued for repository health, dependencies, tests, and ownership." }); if (scan?.id) void runOnboardingScan(scan.id, input.repositoryId); return scan; }),
  }),
  reports: router({
    list: protectedProcedure.input(z.object({ workspaceId: z.number().int().positive() })).query(async ({ ctx, input }) => { await assertWorkspace(ctx.user.id, input.workspaceId); return listEngineeringReports(input.workspaceId); }),
    create: protectedProcedure.input(z.object({ workspaceId: z.number().int().positive(), repositoryId: z.number().int().positive().optional(), summary: z.string().min(1), metrics: z.record(z.string(), z.number()).optional() })).mutation(async ({ ctx, input }) => { await assertWorkspace(ctx.user.id, input.workspaceId); const now = new Date(); const start = new Date(now.getTime() - 7 * 86400000); return createEngineeringReport({ ...input, periodStart: start, periodEnd: now, reportType: "WEEKLY", metrics: input.metrics || {} }); }),
    export: protectedProcedure.input(z.object({ workspaceId: z.number().int().positive(), summary: z.string(), metrics: z.record(z.string(), z.number()).default({}) })).mutation(async ({ ctx, input }) => { await assertWorkspace(ctx.user.id, input.workspaceId); const payload = JSON.stringify({ exportedAt: new Date().toISOString(), workspaceId: input.workspaceId, summary: input.summary, metrics: input.metrics }, null, 2); const stored = await storagePut(`devflow/audit-reports/workspace-${input.workspaceId}.json`, payload, "application/json"); return { ...stored, format: "json" }; }),
  }),
  integrations: router({
    list: protectedProcedure.input(z.object({ workspaceId: z.number().int().positive() })).query(async ({ ctx, input }) => { await assertWorkspace(ctx.user.id, input.workspaceId); const rows = await listIntegrationConfigs(input.workspaceId); return rows.length ? rows : ["SLACK", "EMAIL", "TEAMS", "SEMGREP", "GITLEAKS", "TRIVY"].map(provider => safeExternalAdapter(provider, false)); }),
    save: protectedProcedure.input(z.object({ workspaceId: z.number().int().positive(), provider: z.enum(["SLACK", "EMAIL", "TEAMS", "SEMGREP", "GITLEAKS", "TRIVY"]), target: z.string().optional(), enabled: z.boolean().default(false), config: z.record(z.string(), z.string()).optional() })).mutation(async ({ ctx, input }) => { await assertWorkspace(ctx.user.id, input.workspaceId); return saveIntegrationConfig({ ...input, enabled: input.enabled ? 1 : 0, config: input.config || {} }); }),
    test: protectedProcedure.input(z.object({ workspaceId: z.number().int().positive(), provider: z.enum(["SLACK", "EMAIL", "TEAMS", "SEMGREP", "GITLEAKS", "TRIVY"]), target: z.string().url().optional(), message: z.string().min(1) })).mutation(async ({ ctx, input }) => { await assertWorkspace(ctx.user.id, input.workspaceId); if (["SLACK", "EMAIL", "TEAMS"].includes(input.provider)) return deliverNotification(input.provider as "SLACK" | "EMAIL" | "TEAMS", Boolean(input.target), input.target, input.message); return { status: "NOT_CONFIGURED", message: `${input.provider} adapter is safely staged until a target is configured.` }; }),
  }),
});
export type AppRouter = typeof appRouter;
