import { and, desc, eq } from "drizzle-orm";
import { getDb } from "./db";
import { analysisEvaluations, architectureModules, ciChecks, codeOwners, dependencyRisks, engineeringReports, evaluationDatasets, evaluationSamples, findingLifecycles, githubReviewComments, integrationConfigs, onboardingScans, reviewerAssignments, reviewPolicies, testImpacts } from "../drizzle/schema";

export async function latestReviewPolicy(repositoryId: number) { const db = await getDb(); if (!db) return undefined; const rows = await db.select().from(reviewPolicies).where(eq(reviewPolicies.repositoryId, repositoryId)).orderBy(desc(reviewPolicies.version)).limit(1); return rows[0]; }
export async function saveReviewPolicy(input: typeof reviewPolicies.$inferInsert) { const db = await getDb(); if (!db) return { ...input, id: 0 }; await db.insert(reviewPolicies).values(input); const rows = await db.select().from(reviewPolicies).where(and(eq(reviewPolicies.repositoryId, input.repositoryId), eq(reviewPolicies.version, input.version))).limit(1); return rows[0]; }
export async function saveFindingLifecycle(input: typeof findingLifecycles.$inferInsert) { const db = await getDb(); if (!db) return { ...input, id: 0 }; await db.insert(findingLifecycles).values(input); return input; }
export async function listFindingLifecycle(repositoryId: number) { const db = await getDb(); if (!db) return []; return db.select().from(findingLifecycles).where(eq(findingLifecycles.repositoryId, repositoryId)).orderBy(desc(findingLifecycles.createdAt)).limit(100); }
export async function saveReviewComment(input: typeof githubReviewComments.$inferInsert) { const db = await getDb(); if (!db) return { ...input, id: 0 }; await db.insert(githubReviewComments).values(input); const rows = await db.select().from(githubReviewComments).where(eq(githubReviewComments.findingId, input.findingId)).orderBy(desc(githubReviewComments.createdAt)).limit(1); return rows[0]; }
export async function listReviewComments(repositoryId: number) { const db = await getDb(); if (!db) return []; return db.select().from(githubReviewComments).where(eq(githubReviewComments.repositoryId, repositoryId)).orderBy(desc(githubReviewComments.createdAt)).limit(100); }
export async function saveCodeOwners(repositoryId: number, owners: Array<{ pattern: string; owner: string }>) { const db = await getDb(); if (!db) return owners; for (const owner of owners) await db.insert(codeOwners).values({ repositoryId, pattern: owner.pattern, owner: owner.owner }); return owners; }
export async function listCodeOwners(repositoryId: number) { const db = await getDb(); if (!db) return []; return db.select().from(codeOwners).where(eq(codeOwners.repositoryId, repositoryId)).limit(500); }
export async function saveCiCheck(input: typeof ciChecks.$inferInsert) { const db = await getDb(); if (!db) return { ...input, id: 0 }; await db.insert(ciChecks).values(input); return input; }
export async function listCiChecks(repositoryId: number) { const db = await getDb(); if (!db) return []; return db.select().from(ciChecks).where(eq(ciChecks.repositoryId, repositoryId)).orderBy(desc(ciChecks.createdAt)).limit(100); }
export async function saveArchitectureModules(repositoryId: number, modules: Array<Omit<typeof architectureModules.$inferInsert, "repositoryId">>) { const db = await getDb(); if (!db) return modules; for (const module of modules) await db.insert(architectureModules).values({ ...module, repositoryId }); return modules; }
export async function listArchitectureModules(repositoryId: number) { const db = await getDb(); if (!db) return []; return db.select().from(architectureModules).where(eq(architectureModules.repositoryId, repositoryId)).orderBy(desc(architectureModules.riskScore)).limit(100); }
export async function saveDependencyRisk(input: typeof dependencyRisks.$inferInsert) { const db = await getDb(); if (!db) return { ...input, id: 0 }; await db.insert(dependencyRisks).values(input); return input; }
export async function listDependencyRisks(repositoryId: number) { const db = await getDb(); if (!db) return []; return db.select().from(dependencyRisks).where(eq(dependencyRisks.repositoryId, repositoryId)).orderBy(desc(dependencyRisks.createdAt)).limit(100); }
export async function createOnboardingScan(input: typeof onboardingScans.$inferInsert) { const db = await getDb(); if (!db) return { ...input, id: 0 }; await db.insert(onboardingScans).values(input); return input; }
export async function listOnboardingScans(repositoryId: number) { const db = await getDb(); if (!db) return []; return db.select().from(onboardingScans).where(eq(onboardingScans.repositoryId, repositoryId)).orderBy(desc(onboardingScans.createdAt)).limit(20); }
export async function createEngineeringReport(input: typeof engineeringReports.$inferInsert) { const db = await getDb(); if (!db) return { ...input, id: 0 }; await db.insert(engineeringReports).values(input); return input; }
export async function listEngineeringReports(workspaceId: number) { const db = await getDb(); if (!db) return []; return db.select().from(engineeringReports).where(eq(engineeringReports.workspaceId, workspaceId)).orderBy(desc(engineeringReports.createdAt)).limit(20); }
export async function saveIntegrationConfig(input: typeof integrationConfigs.$inferInsert) { const db = await getDb(); if (!db) return { ...input, id: 0 }; await db.insert(integrationConfigs).values(input); return input; }
export async function listIntegrationConfigs(workspaceId: number) { const db = await getDb(); if (!db) return []; return db.select().from(integrationConfigs).where(eq(integrationConfigs.workspaceId, workspaceId)).orderBy(desc(integrationConfigs.updatedAt)); }

export async function getReviewComment(id: number) { const db = await getDb(); if (!db) return undefined; const rows = await db.select().from(githubReviewComments).where(eq(githubReviewComments.id, id)).limit(1); return rows[0]; }
export async function findPublishedComment(findingId: number) { const db = await getDb(); if (!db) return undefined; const rows = await db.select().from(githubReviewComments).where(and(eq(githubReviewComments.findingId, findingId), eq(githubReviewComments.status, "PUBLISHED"))).limit(1); return rows[0]; }
export async function updateReviewComment(id: number, values: Partial<typeof githubReviewComments.$inferInsert>) { const db = await getDb(); if (db) await db.update(githubReviewComments).set(values).where(eq(githubReviewComments.id, id)); return getReviewComment(id); }
export async function addSecondReleaseAuditLog(input: { workspaceId?: number; userId?: number; action: string; entityType?: string; entityId?: number; metadata?: unknown }) { const db = await getDb(); if (db) await db.insert((await import("../drizzle/schema")).auditLogs).values(input); return input; }

export async function latestLifecycleForFingerprint(repositoryId: number, fingerprint: string) { const db = await getDb(); if (!db) return undefined; const rows = await db.select().from(findingLifecycles).where(and(eq(findingLifecycles.repositoryId, repositoryId), eq(findingLifecycles.fingerprint, fingerprint))).orderBy(desc(findingLifecycles.createdAt)).limit(1); return rows[0]; }
export async function updateFindingLifecycleStatus(findingId: number, lifecycle: "ACCEPTED" | "DISMISSED" | "INACCURATE" | "FIXED" | "REOPENED") { const db = await getDb(); if (!db) return; await db.update(findingLifecycles).set({ lifecycle }).where(eq(findingLifecycles.findingId, findingId)); }
export async function listLatestLifecycleForRepository(repositoryId: number) { const db = await getDb(); if (!db) return []; const rows = await db.select().from(findingLifecycles).where(eq(findingLifecycles.repositoryId, repositoryId)).orderBy(desc(findingLifecycles.createdAt)).limit(500); const latest = new Map<string, (typeof rows)[number]>(); for (const row of rows) if (!latest.has(row.fingerprint)) latest.set(row.fingerprint, row); return Array.from(latest.values()); }

export async function saveTestImpact(input: typeof testImpacts.$inferInsert) { const db = await getDb(); if (!db) return { ...input, id: 0 }; await db.insert(testImpacts).values(input); return input; }
export async function listTestImpacts(analysisId: number) { const db = await getDb(); if (!db) return []; return db.select().from(testImpacts).where(eq(testImpacts.analysisId, analysisId)).orderBy(desc(testImpacts.createdAt)).limit(200); }
export async function createEvaluationDataset(input: typeof evaluationDatasets.$inferInsert) { const db = await getDb(); if (!db) return { ...input, id: 0 }; const result = await db.insert(evaluationDatasets).values(input); return (await db.select().from(evaluationDatasets).where(eq(evaluationDatasets.id, Number(result[0].insertId))).limit(1))[0]; }
export async function listEvaluationDatasets(workspaceId: number) { const db = await getDb(); if (!db) return []; return db.select().from(evaluationDatasets).where(eq(evaluationDatasets.workspaceId, workspaceId)).orderBy(desc(evaluationDatasets.createdAt)); }
export async function saveEvaluationSample(input: typeof evaluationSamples.$inferInsert) { const db = await getDb(); if (!db) return { ...input, id: 0 }; const result = await db.insert(evaluationSamples).values(input); return (await db.select().from(evaluationSamples).where(eq(evaluationSamples.id, Number(result[0].insertId))).limit(1))[0]; }
export async function listEvaluationSamples(datasetId: number) { const db = await getDb(); if (!db) return []; return db.select().from(evaluationSamples).where(eq(evaluationSamples.datasetId, datasetId)).orderBy(desc(evaluationSamples.createdAt)); }
export async function getEvaluationDataset(id: number) { const db = await getDb(); if (!db) return undefined; const rows = await db.select().from(evaluationDatasets).where(eq(evaluationDatasets.id, id)).limit(1); return rows[0]; }
export async function saveReviewerAssignment(input: typeof reviewerAssignments.$inferInsert) { const db = await getDb(); if (!db) return { ...input, id: 0 }; const result = await db.insert(reviewerAssignments).values(input); return (await db.select().from(reviewerAssignments).where(eq(reviewerAssignments.id, Number(result[0].insertId))).limit(1))[0]; }
export async function listReviewerAssignments(pullRequestId: number) { const db = await getDb(); if (!db) return []; return db.select().from(reviewerAssignments).where(eq(reviewerAssignments.pullRequestId, pullRequestId)).orderBy(desc(reviewerAssignments.createdAt)); }
export async function listReviewerAssignmentsForRepository(repositoryId: number) { const db = await getDb(); if (!db) return []; return db.select().from(reviewerAssignments).where(eq(reviewerAssignments.repositoryId, repositoryId)).orderBy(desc(reviewerAssignments.createdAt)).limit(200); }
export async function getReviewerAssignment(id: number) { const db = await getDb(); if (!db) return undefined; const rows = await db.select().from(reviewerAssignments).where(eq(reviewerAssignments.id, id)).limit(1); return rows[0]; }
export async function updateReviewerAssignment(id: number, status: "ASSIGNED" | "DISMISSED") { const db = await getDb(); if (db) await db.update(reviewerAssignments).set({ status }).where(eq(reviewerAssignments.id, id)); return { id, status }; }
export async function saveAnalysisEvaluation(input: typeof analysisEvaluations.$inferInsert) { const db = await getDb(); const normalized = { ...input, datasetName: input.datasetName || "production" }; if (!db) return { ...normalized, id: 0 }; await db.insert(analysisEvaluations).values(normalized); return normalized; }
export async function listAnalysisEvaluations(analysisId: number) { const db = await getDb(); if (!db) return []; return db.select().from(analysisEvaluations).where(eq(analysisEvaluations.analysisId, analysisId)).orderBy(desc(analysisEvaluations.createdAt)).limit(500); }
export async function evaluationSummary(analysisId: number) { const rows = await listAnalysisEvaluations(analysisId); const labeled = rows.filter(row => row.agreement !== null); const falsePositives = rows.filter(row => row.falsePositive === 1).length; const latencies = rows.map(row => row.latencyMs).filter((value): value is number => value !== null).sort((a, b) => a - b); const precision = rows.filter(row => row.reviewerLabel && row.modelLabel).length ? Math.round((rows.filter(row => row.reviewerLabel && row.modelLabel && row.reviewerLabel === row.modelLabel).length / rows.filter(row => row.reviewerLabel && row.modelLabel).length) * 100) : 0; return { samples: rows.length, datasets: Array.from(new Set(rows.map(row => row.datasetName))), agreementRate: labeled.length ? Math.round((labeled.filter(row => row.agreement === 1).length / labeled.length) * 100) : 0, precision, falsePositiveRate: rows.length ? Math.round((falsePositives / rows.length) * 100) : 0, medianLatencyMs: latencies.length ? latencies[Math.floor(latencies.length / 2)] : 0, estimatedCost: rows.reduce((total, row) => total + Number(row.estimatedCost || 0), 0).toFixed(4) }; }

export async function updateOnboardingScan(id: number, values: Partial<typeof onboardingScans.$inferInsert>) { const db = await getDb(); if (db) await db.update(onboardingScans).set(values).where(eq(onboardingScans.id, id)); return onboardingScans; }
