import crypto from "node:crypto";
import { z } from "zod";

export const reviewPolicySchema = z.object({ minimumBlockingSeverity: z.enum(["critical", "high", "medium", "low", "info"]).default("critical"), requireTestsFor: z.array(z.string()).default(["server/**", "api/**", "db/**"]), ignoredPaths: z.array(z.string()).default(["dist/**", "**/*.snap"]), enabledPrechecks: z.array(z.string()).default(["missing-tests", "large-pr", "secrets", "migrations", "authorization"]), maximumPrSize: z.number().int().positive().max(10000).default(800), blockOnSecrets: z.boolean().default(true), postInlineComments: z.boolean().default(false) });
export type ReviewPolicyInput = z.infer<typeof reviewPolicySchema>;

export function normalizePolicy(input: Partial<ReviewPolicyInput>) { return reviewPolicySchema.parse(input); }
export function findingFingerprint(input: { category: string; filePath?: string | null; title: string; evidence: string }) { return crypto.createHash("sha256").update([input.category, input.filePath || "", input.title, input.evidence].join("\n")).digest("hex"); }
export function deriveFindingLifecycle(previous: { fingerprint: string; status?: string } | undefined, currentFingerprint: string) { if (!previous) return "NEW" as const; if (previous.fingerprint !== currentFingerprint) return "NEW" as const; if (previous.status === "ACCEPTED") return "ACCEPTED" as const; if (previous.status === "DISMISSED") return "DISMISSED" as const; if (previous.status === "INACCURATE") return "INACCURATE" as const; return "RECURRING" as const; }

export function parseCodeowners(content: string) { return content.split(/\r?\n/).map(line => line.trim()).filter(line => line && !line.startsWith("#")).flatMap(line => { const [pattern, ...owners] = line.split(/\s+/); return owners.map(owner => ({ pattern, owner })); }); }
export function ownerMatches(pattern: string, filePath: string) { const escaped = pattern.replace(/[.+^${}()|[\]\\]/g, "\\$&").replace(/\*\*/g, "§§").replace(/\*/g, "[^/]*").replace(/§§/g, ".*"); return new RegExp(`^${escaped}$`).test(filePath) || new RegExp(`(^|/)${escaped}$`).test(filePath); }
export function impactedTests(files: string[], availableTests: string[]) { return files.map(changedFile => ({ changedFile, impactedTest: availableTests.find(test => { const base = changedFile.split("/").at(-1)?.split(".")[0] || ""; return test.toLowerCase().includes(base.toLowerCase()); }), coverageAvailable: availableTests.some(test => test.toLowerCase().includes((changedFile.split("/").at(-1)?.split(".")[0] || "").toLowerCase())), confidence: availableTests.length ? "0.72" : "0.31" })); }
export function architectureModules(files: string[]) { const groups = new Map<string, string[]>(); for (const file of files) { const parts = file.split("/"); const modulePath = parts.length > 1 ? parts.slice(0, Math.min(2, parts.length - 1)).join("/") : "root"; groups.set(modulePath, [...(groups.get(modulePath) || []), file]); } return Array.from(groups.entries()).map(([modulePath, moduleFiles]: [string, string[]]) => ({ modulePath, language: moduleFiles.some((file: string) => file.endsWith(".ts")) ? "TypeScript" : moduleFiles.some((file: string) => file.endsWith(".py")) ? "Python" : "Mixed", fileCount: moduleFiles.length, dependencyCount: 0, riskScore: Math.min(100, moduleFiles.length * 8), hotspotScore: Math.min(100, moduleFiles.length * 10) })); }
export function safeExternalAdapter(provider: string, configured: boolean) { return { provider, configured, enabled: configured, status: configured ? "READY" : "NOT_CONFIGURED" as const }; }
export function selectOwnerRecipientIds(ownerNames: string[], members: Array<{ userId: number; name?: string | null; email?: string | null }>, fallbackIds: number[]) { const normalizedOwners = ownerNames.map(owner => owner.replace(/^@/, "").toLowerCase()); const matched = members.filter(member => normalizedOwners.some(owner => [member.name, member.email].filter(Boolean).some(value => value!.toLowerCase().replace(/^@/, "").includes(owner)))).map(member => member.userId); return matched.length ? Array.from(new Set(matched)) : fallbackIds; }
export function evaluationPrecision(rows: Array<{ reviewerLabel?: string | null; modelLabel?: string | null }>) { const labeled = rows.filter(row => row.reviewerLabel && row.modelLabel); return labeled.length ? Math.round((labeled.filter(row => row.reviewerLabel === row.modelLabel).length / labeled.length) * 100) : 0; }
export function policyBlocksFindings(policy: ReviewPolicyInput, findings: Array<{ severity: string; category: string }>) { const order = ["info", "low", "medium", "high", "critical"]; const threshold = order.indexOf(policy.minimumBlockingSeverity); return findings.filter(finding => (policy.blockOnSecrets && finding.category === "security" && finding.severity === "critical") || order.indexOf(finding.severity) >= threshold); }
